package view;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.lang.*;
import javax.swing.*;
import java.awt.*;
import static javax.swing.JOptionPane.showMessageDialog;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import model.*;

public class Reg extends javax.swing.JFrame {

    public static String gender;
    public static String blood_type;
    /**
     * Creates new form reg
     */
    public Reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtE = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        rM = new javax.swing.JRadioButton();
        rF = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cB = new javax.swing.JComboBox<>();
        pP = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pR = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dateofbirth = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 50));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        txtE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 622, 40));

        txtN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNActionPerformed(evt);
            }
        });
        getContentPane().add(txtN, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 622, 44));

        rM.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        rM.setText("Male");
        rM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rMActionPerformed(evt);
            }
        });
        getContentPane().add(rM, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 108, -1));

        rF.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        rF.setText("Female");
        rF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFActionPerformed(evt);
            }
        });
        getContentPane().add(rF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 108, -1));

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date of birth");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 33));

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood Group");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        cB.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        cB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Blood Group>", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        cB.setToolTipText("");
        cB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBActionPerformed(evt);
            }
        });
        getContentPane().add(cB, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 389, 196, 32));

        pP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pP, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 437, 180, -1));

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 124, -1));

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Re-enter Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 250, -1));

        pR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pR, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 197, 39));

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 174, 50));

        jButton2.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("<<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 170, 50));
        getContentPane().add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 190, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reg.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNActionPerformed

    private void cBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new DLogin().setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email,name,dob,pass,repass;    
        
             email = txtE.getText().trim();
            Component frame = null;

        // Check if the email is empty
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Email is required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        String fullName = txtN.getText().trim();

        String lettersOnlyRegex = "^[a-zA-Z\\s]+$";
        
        try {
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(frame, "Invalid email format", "Error", JOptionPane.ERROR_MESSAGE);
            }
        else if ("".equals(txtE.getText())) {
        JOptionPane.showMessageDialog(new JFrame(), "Email is required", "Error", JOptionPane.ERROR_MESSAGE);
         } else if ("".equals(txtN.getText())) {
        JOptionPane.showMessageDialog(new JFrame(), "Full Name is required", "Error", JOptionPane.ERROR_MESSAGE);
         } else if (!fullName.matches(lettersOnlyRegex)) {
        JOptionPane.showMessageDialog(new JFrame(), "Full Name should contain only letters", "Error", JOptionPane.ERROR_MESSAGE);
        // You might want to clear the text field or take appropriate action here
        } 
        else if (!(rM.isSelected() || rF.isSelected())) {
        // No gender selected, show an error message
        JOptionPane.showMessageDialog(new JFrame(), "Please select a gender", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (cB.getSelectedIndex() == -1 || cB.getSelectedIndex() == 0) {
        // No blood type selected, show an error message
        JOptionPane.showMessageDialog(new JFrame(), "Please select your Blood", "Error", JOptionPane.ERROR_MESSAGE);
         }else if(dateofbirth.getDate() == null){
             JOptionPane.showMessageDialog(new JFrame(), "Date is required", "Error", JOptionPane.ERROR_MESSAGE);
         }
        else if ("".equals(pP.getText()) || "".equals(pR.getText())){ 
        JOptionPane.showMessageDialog(new JFrame(), "Provide your password!!!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!pP.getText().equals(pR.getText())) {
        JOptionPane.showMessageDialog(new JFrame(), "Password Mismatch", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
        String query = "INSERT INTO user(email, name, gender, dob, blood_group, pass) VALUES(?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement= DBConnection.getMyConnection().prepareStatement(query); 
            preparedStatement.setString(1, txtE.getText());
            preparedStatement.setString(2, txtN.getText());
            preparedStatement.setString(3, gender);
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dobText = dateFormat.format( dateofbirth.getDate());
            preparedStatement.setString(4, dobText);
            preparedStatement.setString(5, cB.getSelectedItem().toString());
            preparedStatement.setString(6, pP.getText());
           int rowsAffected = preparedStatement.executeUpdate();
        
            
        // Clear form fields
       if (rowsAffected > 0) {
            // Clear form fields
            txtE.setText("");
            txtN.setText("");
            rM.setSelected(false);
            rF.setSelected(false);
            dateofbirth.setDate(null);
            cB.setSelectedIndex(0);
            pP.setText("");
            pR.setText("");

            JOptionPane.showMessageDialog(null, "New account has been created successfully!");
            this.dispose();
            new DLogin().setVisible(true);
        } 
       else {
            JOptionPane.showMessageDialog(new JFrame(), "Error in database operation", "Error", JOptionPane.ERROR_MESSAGE);
       }
        
    }
        } 
        catch (SQLException e) {
    // Handle SQL exception
    e.printStackTrace();
    }

        catch(Exception e){
           System.out.println("Error! " + e.getMessage()); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rMActionPerformed
        gender = "Male";
        rF.setSelected(false);
    }//GEN-LAST:event_rMActionPerformed

    private void rFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFActionPerformed
        gender = "Female";
        rM.setSelected(false);
    }//GEN-LAST:event_rFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cB;
    private com.toedter.calendar.JDateChooser dateofbirth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JPasswordField pP;
    private javax.swing.JPasswordField pR;
    private javax.swing.JRadioButton rF;
    private javax.swing.JRadioButton rM;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextField txtN;
    // End of variables declaration//GEN-END:variables

    private String hashPassword(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
